title: twelfthlane.net -12th-ln-&gt;
permalink: /:year/:month/:day/:title
url: http://twelfthlane.net
contact-links:
  skype: live:velanixon
  telegram: velanixon
  email: velanixon@outlook.com
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
